version: '3'

services:
    portainer-agent:
        image: portainer/agent:2.26.1-alpine
        restart: unless-stopped
        ports:
            - 9001:9001
        environment:
            - AGENT_SECRET=${AGENT_SECRET}
#            - CAP_HOST_MANAGEMENT=1 # включите функции управления хостом, установив значение 1
#            - AGENT_CLUSTER_ADDR=tasks.<AGENT_SERVICE_NAME> Адрес, используемый каждым агентом для формирования кластера. Рекомендуется установить это значение tasks.<AGENT_SERVICE_NAME>при развертывании агента внутри кластера Swarm.
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
            - /:/host

